- name: hello copy
  hosts: agents
  gather_facts: no
  tasks:
    - name: test create directory
      file:
        path: test
        state: directory
        #state: absent
    - name: test copy file
      copy:
        src: test.txt
        dest: test/test.txt
        backup: yes
