- name: hello net tools
  hosts: agents
  gather_facts: no
  tasks:
    - name: test get_url
      get_url:
        url: http://nginx.org/download/nginx-1.20.0.tar.gz
        dest: /home/vagrant/
        checksum: sha256:54ef91ec8ebcaa486c640c09c92d832eaeaff149b10ee52ef140f407b1b04d1c
    - name: test unarchive remote
      unarchive:
        src: /home/vagrant/nginx-1.20.0.tar.gz
        dest: /home/vagrant/
        remote_src: yes
    - name: test scp and unarchive remote
      unarchive:
        src: inventory.tar.gz
        dest: /home/vagrant/
